"""empty message

Revision ID: 29111d5011b1
Revises: 
Create Date: 2019-07-25 11:46:01.372297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29111d5011b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fractals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('division_order', sa.Integer(), nullable=False),
    sa.Column('lon1', sa.DECIMAL(), nullable=False),
    sa.Column('lat1', sa.DECIMAL(), nullable=False),
    sa.Column('lon2', sa.DECIMAL(), nullable=False),
    sa.Column('lat2', sa.DECIMAL(), nullable=False),
    sa.Column('lon3', sa.DECIMAL(), nullable=False),
    sa.Column('lat3', sa.DECIMAL(), nullable=False),
    sa.Column('lon4', sa.DECIMAL(), nullable=False),
    sa.Column('lat4', sa.DECIMAL(), nullable=False),
    sa.Column('lon5', sa.DECIMAL(), nullable=False),
    sa.Column('lat5', sa.DECIMAL(), nullable=False),
    sa.Column('lon6', sa.DECIMAL(), nullable=False),
    sa.Column('lat6', sa.DECIMAL(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fractals')
    # ### end Alembic commands ###
